comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
ignore:
  - "**/*_unittest.cc"
  - "src/*_unittest/**"
  - "src/googletest.h"
  - "src/mock-log.h"
