name: Android

on: [push, pull_request]

jobs:
  build:
    name: NDK-C++${{matrix.std}}-${{matrix.abi}}-${{matrix.build_type}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          std: [98, 11, 14, 17, 20]
          abi: [arm64-v8a, armeabi-v7a, x86_64, x86]
          build_type: [Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.10.0

    - name: Configure
      shell: bash
      run: |
        cmake -S . -B ${{runner.workspace}}/build_CXX${{matrix.std}}-${{matrix.abi}} \
              -G "Ninja Multi-Config" \
              -DCMAKE_CXX_EXTENSIONS=OFF \
              -DCMAKE_CXX_STANDARD=${{matrix.std}} \
              -DCMAKE_CXX_STANDARD_REQUIRED=ON \
              -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake \
              -DANDROID_STL=c++_shared \
              -DANDROID_NATIVE_API_LEVEL=28 \
              -DANDROID_ABI=${{matrix.abi}} \
    - name: Build
      run: |
        cmake --build ${{runner.workspace}}/build_CXX${{matrix.std}}-${{matrix.abi}} \
              --config ${{matrix.build_type}}

